receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: '0.0.0.0:4318'

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317  # Send traces to Jaeger via OTLP at port 4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"  # Expose Prometheus metrics

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
